---
title: "Reproducible Pitch Presentation"
output: 
  ioslides_presentation: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Use of Application
- To demonstrates how a distribution of randomly generated numbers approximate normal distribution when number of observations gets large

## User Interface

```{r, echo=FALSE}
library(shiny)

shinyApp(

  ui = shinyUI(pageWithSidebar(
    
    headerPanel("Normal Approximation"),
    
    sidebarPanel(
        sliderInput("obs", 
                    "Number of observations:", 
                    min = 1,
                    max = 1000, 
                    value = 500)
    ),
    
    mainPanel(
        plotOutput("distPlot")
    )
)),

  server = shinyServer(function(input, output) {
    
    output$distPlot <- renderPlot({
        dist <- rnorm(input$obs)
        hist(dist)
    })
}),

)
```

## Small Observations

```{r, echo=FALSE}
library(shiny)

shinyApp(

  ui = shinyUI(pageWithSidebar(
    
    headerPanel("Normal Approximation"),
    
    sidebarPanel(
        sliderInput("obs", 
                    "Number of observations:", 
                    min = 1,
                    max = 1000, 
                    value = 50)
    ),
    
    mainPanel(
        plotOutput("distPlot")
    )
)),

  server = shinyServer(function(input, output) {
    
    output$distPlot <- renderPlot({
        dist <- rnorm(input$obs)
        hist(dist)
    })
}),

)
```


## Large Observations (Normal Distribution Approximation)

```{r, echo=FALSE}
library(shiny)

shinyApp(

  ui = shinyUI(pageWithSidebar(
    
    headerPanel("Normal Approximation"),
    
    sidebarPanel(
        sliderInput("obs", 
                    "Number of observations:", 
                    min = 1,
                    max = 1000, 
                    value = 900)
    ),
    
    mainPanel(
        plotOutput("distPlot")
    )
)),

  server = shinyServer(function(input, output) {
    
    output$distPlot <- renderPlot({
        dist <- rnorm(input$obs)
        hist(dist)
    })
}),

)
```